# Generated by Django 4.2.8 on 2025-12-07 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('moeda', 'Moeda (Dolar, Euro, etc)'), ('indice', 'Indice (IGPM, INPC, etc)'), ('produto', 'Produto (Cesta Basica, etc)'), ('outro', 'Outro')], max_length=20)),
                ('unidade', models.CharField(max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('fonte_api', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Indicadores',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='ValorIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=10)),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
                ('fonte', models.CharField(choices=[('api', 'API automática'), ('manual', 'Cadastro manual'), ('scraping', 'Web scraping')], max_length=100)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='indicadores.indicador')),
            ],
            options={
                'verbose_name_plural': 'Valores de Indicadores',
                'ordering': ['-data_coleta'],
            },
        ),
    ]
