# Generated by Django 6.0 on 2025-12-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='tipo',
            field=models.CharField(choices=[('Moeda', 'Moeda (Dolar, Euro, etc)'), ('Indice', 'Indice (IGPM, INPC, etc)'), ('Produto', 'Produto (Cesta Basica, etc)'), ('Outro', 'Outro')], max_length=20),
        ),
    ]
